name: cache_manager_lite_example
description: Examples for Cache Manager Lite package.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  cache_manager_lite:
    path: ../
  cupertino_icons: ^1.0.6
  dio: ^5.4.0
  riverpod: ^2.4.10
  flutter_riverpod: ^2.4.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
