name: cache_manager_lite
description: "A high-performance, user-friendly, and secure cache manager for Flutter, designed for maximum flexibility and developer productivity."
version: 0.1.2
homepage: https://github.com/Kidpech-code/cache_manager_lite
repository: https://github.com/Kidpech-code/cache_manager_lite
issue_tracker: https://github.com/Kidpech-code/cache_manager_lite/issues
documentation: https://github.com/Kidpech-code/cache_manager_lite#readme

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  hive: ^2.2.3
  dio: ^5.7.0
  encrypt: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
